---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/water_considerations/water_considerations.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/199825/master/file/figures/water_considerations/water_considerations.csv"
    folder_url: "/users/2191/articles/199825/master/folder/figures/water_considerations"
