---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/2241796494_989841dda1/2241796494_989841dda1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/199825/master/file/figures/2241796494_989841dda1/2241796494_989841dda1.png"
